# theme = "plain"
# icons = "awesome6"
[theme]
theme = "plain"
[icons]
icons = "awesome6"

[[block]]
block = "net"
format = " ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) $icon {$signal_strength $device: $ssid /$frequency  |$device: Wired connection} "

[[block]]
block = "disk_space"
path = "/"
format= " $icon $percentage "
info_type = "used"
interval = 20
warning = 85.0
alert = 95.0

[[block]]
block = "memory"
format= " $icon $mem_total_used_percents.eng(w:2) "

[[block]]
block = "load"
interval = 1

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
interval = 2
warning = 90
info = 80
good = 50
inputs = ["Tctl"]
format = " $icon $max "

[[block]]
block = "sound"
driver = "pulseaudio"
show_volume_when_muted = false
#name = "alsa_output.usb-Yamaha_Corporation_Steinberg_UR22mkII-00.analog-stereo"

[[block]]
block = "time"
interval = 60
# format = "%a %d.%m %R"

[[block]]
block = "battery"
missing_format = ""
format = "$icon $percentage"
full_format = "$icon $percentage"
empty_format = "$icon $percentage"

