#!/usr/bin/bash

readarray -t monitors < <(xrandr --listmonitors | tail +2 | awk '{print $2}')
declare -a args=()
for monitor in "${monitors[@]}"; do
    args+=(--delmonitor "${monitor}")
done

n_monitors=${1:-3}

if [ $n_monitors -ge 1 ]; then
    args+=(--setmonitor default~1 1920/508x1200/317+0+0 default)
fi

if [ $n_monitors -ge 2 ]; then
    args+=(--setmonitor default~2 1920/508x1200/317+1920+0 none)
fi

if [ $n_monitors -ge 3 ]; then
    args+=(--setmonitor default~3 1920/508x1200/317+3840+0 none)
fi

echo xrandr "${args[@]}"
xrandr "${args[@]}"
