#!/usr/bin/bash

i3lock \
    -c003344 \
    --time-color=#ffffff88 \
    --date-color=#ffffff66 \
    --clock \
    --time-str="%H:%M" \
    --date-str="%d %B %Y" \
    --ignore-empty-password \
    --inside-color=00000000 \
    --insidever-color=00000000 \
    --layout-color=ff0000 \
    --line-color=00000055 \
    --wrong-color=ffffff88 \
    --wrong-text="" \
    --verif-text="..." \
    --verif-color=#ffffff66 \
    --wrong-color=#ffffff88 \
    --wrong-size=16


